// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: forge/v1/ca.proto

package forgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_forge_v1_ca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_ca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_forge_v1_ca_proto_rawDescGZIP(), []int{0}
}

type IssueCertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BootstrapToken string                 `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	ServiceName    string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Csr            []byte                 `protobuf:"bytes,3,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IssueCertRequest) Reset() {
	*x = IssueCertRequest{}
	mi := &file_forge_v1_ca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCertRequest) ProtoMessage() {}

func (x *IssueCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_ca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCertRequest.ProtoReflect.Descriptor instead.
func (*IssueCertRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_ca_proto_rawDescGZIP(), []int{1}
}

func (x *IssueCertRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *IssueCertRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *IssueCertRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type RenewCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Csr           []byte                 `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertRequest) Reset() {
	*x = RenewCertRequest{}
	mi := &file_forge_v1_ca_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertRequest) ProtoMessage() {}

func (x *RenewCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_ca_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertRequest.ProtoReflect.Descriptor instead.
func (*RenewCertRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_ca_proto_rawDescGZIP(), []int{2}
}

func (x *RenewCertRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_forge_v1_ca_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_ca_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_ca_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RevokeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_forge_v1_ca_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_ca_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_ca_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RevokeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	RootCa        []byte                 `protobuf:"bytes,2,opt,name=root_ca,json=rootCa,proto3" json:"root_ca,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertResponse) Reset() {
	*x = CertResponse{}
	mi := &file_forge_v1_ca_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertResponse) ProtoMessage() {}

func (x *CertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_ca_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertResponse.ProtoReflect.Descriptor instead.
func (*CertResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_ca_proto_rawDescGZIP(), []int{5}
}

func (x *CertResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *CertResponse) GetRootCa() []byte {
	if x != nil {
		return x.RootCa
	}
	return nil
}

func (x *CertResponse) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *CertResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type RootCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       []byte                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootCertResponse) Reset() {
	*x = RootCertResponse{}
	mi := &file_forge_v1_ca_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCertResponse) ProtoMessage() {}

func (x *RootCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_ca_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCertResponse.ProtoReflect.Descriptor instead.
func (*RootCertResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_ca_proto_rawDescGZIP(), []int{6}
}

func (x *RootCertResponse) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *RootCertResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RootCertResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_forge_v1_ca_proto protoreflect.FileDescriptor

const file_forge_v1_ca_proto_rawDesc = "" +
	"\n" +
	"\x11forge/v1/ca.proto\x12\bforge.v1\"\a\n" +
	"\x05Empty\"p\n" +
	"\x10IssueCertRequest\x12'\n" +
	"\x0fbootstrap_token\x18\x01 \x01(\tR\x0ebootstrapToken\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03csr\x18\x03 \x01(\fR\x03csr\"$\n" +
	"\x10RenewCertRequest\x12\x10\n" +
	"\x03csr\x18\x01 \x01(\fR\x03csr\"?\n" +
	"\rRevokeRequest\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\":\n" +
	"\x0eRevokeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x80\x01\n" +
	"\fCertResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x17\n" +
	"\aroot_ca\x18\x02 \x01(\fR\x06rootCa\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"f\n" +
	"\x10RootCertResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\fR\acertPem\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt2\x95\x02\n" +
	"\x14CertificateAuthority\x12?\n" +
	"\tIssueCert\x12\x1a.forge.v1.IssueCertRequest\x1a\x16.forge.v1.CertResponse\x12?\n" +
	"\tRenewCert\x12\x1a.forge.v1.RenewCertRequest\x1a\x16.forge.v1.CertResponse\x12?\n" +
	"\n" +
	"RevokeCert\x12\x17.forge.v1.RevokeRequest\x1a\x18.forge.v1.RevokeResponse\x12:\n" +
	"\vGetRootCert\x12\x0f.forge.v1.Empty\x1a\x1a.forge.v1.RootCertResponseB,Z*github.com/paladimo/sigil/forge/v1;forgev1b\x06proto3"

var (
	file_forge_v1_ca_proto_rawDescOnce sync.Once
	file_forge_v1_ca_proto_rawDescData []byte
)

func file_forge_v1_ca_proto_rawDescGZIP() []byte {
	file_forge_v1_ca_proto_rawDescOnce.Do(func() {
		file_forge_v1_ca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forge_v1_ca_proto_rawDesc), len(file_forge_v1_ca_proto_rawDesc)))
	})
	return file_forge_v1_ca_proto_rawDescData
}

var file_forge_v1_ca_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_forge_v1_ca_proto_goTypes = []any{
	(*Empty)(nil),            // 0: forge.v1.Empty
	(*IssueCertRequest)(nil), // 1: forge.v1.IssueCertRequest
	(*RenewCertRequest)(nil), // 2: forge.v1.RenewCertRequest
	(*RevokeRequest)(nil),    // 3: forge.v1.RevokeRequest
	(*RevokeResponse)(nil),   // 4: forge.v1.RevokeResponse
	(*CertResponse)(nil),     // 5: forge.v1.CertResponse
	(*RootCertResponse)(nil), // 6: forge.v1.RootCertResponse
}
var file_forge_v1_ca_proto_depIdxs = []int32{
	1, // 0: forge.v1.CertificateAuthority.IssueCert:input_type -> forge.v1.IssueCertRequest
	2, // 1: forge.v1.CertificateAuthority.RenewCert:input_type -> forge.v1.RenewCertRequest
	3, // 2: forge.v1.CertificateAuthority.RevokeCert:input_type -> forge.v1.RevokeRequest
	0, // 3: forge.v1.CertificateAuthority.GetRootCert:input_type -> forge.v1.Empty
	5, // 4: forge.v1.CertificateAuthority.IssueCert:output_type -> forge.v1.CertResponse
	5, // 5: forge.v1.CertificateAuthority.RenewCert:output_type -> forge.v1.CertResponse
	4, // 6: forge.v1.CertificateAuthority.RevokeCert:output_type -> forge.v1.RevokeResponse
	6, // 7: forge.v1.CertificateAuthority.GetRootCert:output_type -> forge.v1.RootCertResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forge_v1_ca_proto_init() }
func file_forge_v1_ca_proto_init() {
	if File_forge_v1_ca_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forge_v1_ca_proto_rawDesc), len(file_forge_v1_ca_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forge_v1_ca_proto_goTypes,
		DependencyIndexes: file_forge_v1_ca_proto_depIdxs,
		MessageInfos:      file_forge_v1_ca_proto_msgTypes,
	}.Build()
	File_forge_v1_ca_proto = out.File
	file_forge_v1_ca_proto_goTypes = nil
	file_forge_v1_ca_proto_depIdxs = nil
}
