// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: vault/v1/sm.proto

package vaultv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretRequest) Reset() {
	*x = SetSecretRequest{}
	mi := &file_vault_v1_sm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretRequest) ProtoMessage() {}

func (x *SetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretRequest.ProtoReflect.Descriptor instead.
func (*SetSecretRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{0}
}

func (x *SetSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSecretRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetSecretRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretResponse) Reset() {
	*x = SetSecretResponse{}
	mi := &file_vault_v1_sm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretResponse) ProtoMessage() {}

func (x *SetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretResponse.ProtoReflect.Descriptor instead.
func (*SetSecretResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{1}
}

func (x *SetSecretResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetSecretResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSecretResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_vault_v1_sm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_vault_v1_sm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetSecretResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetSecretResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_vault_v1_sm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteSecretRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_vault_v1_sm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSecretResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteSecretResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_vault_v1_sm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{6}
}

func (x *ListSecretsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretMeta          `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_vault_v1_sm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{7}
}

func (x *ListSecretsResponse) GetSecrets() []*SecretMeta {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type SecretMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMeta) Reset() {
	*x = SecretMeta{}
	mi := &file_vault_v1_sm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMeta) ProtoMessage() {}

func (x *SecretMeta) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMeta.ProtoReflect.Descriptor instead.
func (*SecretMeta) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{8}
}

func (x *SecretMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SecretMeta) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SecretMeta) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type WatchSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSecretRequest) Reset() {
	*x = WatchSecretRequest{}
	mi := &file_vault_v1_sm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSecretRequest) ProtoMessage() {}

func (x *WatchSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSecretRequest.ProtoReflect.Descriptor instead.
func (*WatchSecretRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{9}
}

func (x *WatchSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type WatchSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Event         string                 `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSecretResponse) Reset() {
	*x = WatchSecretResponse{}
	mi := &file_vault_v1_sm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSecretResponse) ProtoMessage() {}

func (x *WatchSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_sm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSecretResponse.ProtoReflect.Descriptor instead.
func (*WatchSecretResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_sm_proto_rawDescGZIP(), []int{10}
}

func (x *WatchSecretResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchSecretResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WatchSecretResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *WatchSecretResponse) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

var File_vault_v1_sm_proto protoreflect.FileDescriptor

const file_vault_v1_sm_proto_rawDesc = "" +
	"\n" +
	"\x11vault/v1/sm.proto\x12\bvault.v1\"L\n" +
	"\x10SetSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\"T\n" +
	"\x11SetSecretResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"$\n" +
	"\x10GetSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"Z\n" +
	"\x11GetSecretResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"?\n" +
	"\x13DeleteSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"@\n" +
	"\x14DeleteSecretResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x12ListSecretsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"E\n" +
	"\x13ListSecretsResponse\x12.\n" +
	"\asecrets\x18\x01 \x03(\v2\x14.vault.v1.SecretMetaR\asecrets\"\\\n" +
	"\n" +
	"SecretMeta\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"&\n" +
	"\x12WatchSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"r\n" +
	"\x13WatchSecretResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event2\xfc\x02\n" +
	"\x05Vault\x12D\n" +
	"\tSetSecret\x12\x1a.vault.v1.SetSecretRequest\x1a\x1b.vault.v1.SetSecretResponse\x12D\n" +
	"\tGetSecret\x12\x1a.vault.v1.GetSecretRequest\x1a\x1b.vault.v1.GetSecretResponse\x12M\n" +
	"\fDeleteSecret\x12\x1d.vault.v1.DeleteSecretRequest\x1a\x1e.vault.v1.DeleteSecretResponse\x12J\n" +
	"\vListSecrets\x12\x1c.vault.v1.ListSecretsRequest\x1a\x1d.vault.v1.ListSecretsResponse\x12L\n" +
	"\vWatchSecret\x12\x1c.vault.v1.WatchSecretRequest\x1a\x1d.vault.v1.WatchSecretResponse0\x01B,Z*github.com/paladimo/sigil/vault/v1;vaultv1b\x06proto3"

var (
	file_vault_v1_sm_proto_rawDescOnce sync.Once
	file_vault_v1_sm_proto_rawDescData []byte
)

func file_vault_v1_sm_proto_rawDescGZIP() []byte {
	file_vault_v1_sm_proto_rawDescOnce.Do(func() {
		file_vault_v1_sm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_v1_sm_proto_rawDesc), len(file_vault_v1_sm_proto_rawDesc)))
	})
	return file_vault_v1_sm_proto_rawDescData
}

var file_vault_v1_sm_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vault_v1_sm_proto_goTypes = []any{
	(*SetSecretRequest)(nil),     // 0: vault.v1.SetSecretRequest
	(*SetSecretResponse)(nil),    // 1: vault.v1.SetSecretResponse
	(*GetSecretRequest)(nil),     // 2: vault.v1.GetSecretRequest
	(*GetSecretResponse)(nil),    // 3: vault.v1.GetSecretResponse
	(*DeleteSecretRequest)(nil),  // 4: vault.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 5: vault.v1.DeleteSecretResponse
	(*ListSecretsRequest)(nil),   // 6: vault.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),  // 7: vault.v1.ListSecretsResponse
	(*SecretMeta)(nil),           // 8: vault.v1.SecretMeta
	(*WatchSecretRequest)(nil),   // 9: vault.v1.WatchSecretRequest
	(*WatchSecretResponse)(nil),  // 10: vault.v1.WatchSecretResponse
}
var file_vault_v1_sm_proto_depIdxs = []int32{
	8,  // 0: vault.v1.ListSecretsResponse.secrets:type_name -> vault.v1.SecretMeta
	0,  // 1: vault.v1.Vault.SetSecret:input_type -> vault.v1.SetSecretRequest
	2,  // 2: vault.v1.Vault.GetSecret:input_type -> vault.v1.GetSecretRequest
	4,  // 3: vault.v1.Vault.DeleteSecret:input_type -> vault.v1.DeleteSecretRequest
	6,  // 4: vault.v1.Vault.ListSecrets:input_type -> vault.v1.ListSecretsRequest
	9,  // 5: vault.v1.Vault.WatchSecret:input_type -> vault.v1.WatchSecretRequest
	1,  // 6: vault.v1.Vault.SetSecret:output_type -> vault.v1.SetSecretResponse
	3,  // 7: vault.v1.Vault.GetSecret:output_type -> vault.v1.GetSecretResponse
	5,  // 8: vault.v1.Vault.DeleteSecret:output_type -> vault.v1.DeleteSecretResponse
	7,  // 9: vault.v1.Vault.ListSecrets:output_type -> vault.v1.ListSecretsResponse
	10, // 10: vault.v1.Vault.WatchSecret:output_type -> vault.v1.WatchSecretResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_vault_v1_sm_proto_init() }
func file_vault_v1_sm_proto_init() {
	if File_vault_v1_sm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_v1_sm_proto_rawDesc), len(file_vault_v1_sm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_v1_sm_proto_goTypes,
		DependencyIndexes: file_vault_v1_sm_proto_depIdxs,
		MessageInfos:      file_vault_v1_sm_proto_msgTypes,
	}.Build()
	File_vault_v1_sm_proto = out.File
	file_vault_v1_sm_proto_goTypes = nil
	file_vault_v1_sm_proto_depIdxs = nil
}
